### ISSUE TITLE
Integration with Whatsapp

### ISSUE THREAD

**Issue by ognjen011** [Swatto/promtotwilio#8]
Could this be used to send notification via twilio to whatsapp rather than SMS only?

**Comment by Swatto** [comment]
From what I see, Twilio has integration with WhatsApp. You can make them sending a message to specific numbers by "just" setting a prefix as `whatsapp:+xxxxxxxx`.

I don't have the setup to validate it for you but if you are interested, feel free to follow the [official documentation](https://www.twilio.com/docs/whatsapp) to setup your Twilio account as it should. I'm very interested in your results.

Warning, it looks like integrating WhatsApp with "bot" is a paid product on WhatsApp end on their [Business API](https://www.whatsapp.com/business/api/)

**Comment by ognjen011** [comment]
Ok i will give it a shot. I have an account and already using whatsapp notifications from other systems. It would be nice if i could make this work.

**Comment by ognjen011** [comment]
SMS works but i am unsure whats the best way to add the prefix whatsapp: and where? Should it be in .env because i tried that and it didn't work. Or should prefix go to options_with_handler.go somewhere?

**Comment by ognjen011** [comment]
Ok i was able to send whatsapp  via twilio by adding prefix whatsapp:. Just need to figure out alertmanager where to setup prefix as well.

**Comment by Swatto** [comment]
As explained in the README, `RECEIVER` environment variable is used to know the number to text. Why don't you try to set the prefix at that level?

**Comment by ognjen011** [comment]
This is working with whatsapp i have only picked up two issues but that could be  my config. First it only sends summary not an entire alert and so there is no [FIRING] or [RESOLVED] label although email and slack both work as expected. The second is send_resolved: true does not seem to have any effect. 

My setup looks like this:

 webhook_configs:
  - url: 'http://loclahost:9090/send?receiver=whatsapp:%2B1111111111'
    send_resolved: true
